FROM golang:1.11 as builder

WORKDIR /go/src/app/

COPY *.go ./
ENTRYPOINT [ "/go/src/app/hello" ]

RUN go test -v -cover
RUN go build -ldflags "-extldflags \"-static\"" -o hello

FROM scratch as final

ENTRYPOINT [ "/go/src/app/hello" ]
COPY --from=builder /go/src/app/hello /go/src/app/hello
